export const ZIMBABWE_TRADE_HUBS = [
  'Chiredzi Town',
  'Tshovani Town',
  'Hippo Valley Estate',
  'Triangle Estate',
  'Mkwasine',
  'Buffalo Range',
  'Malipati',
  'Checheche Growth Point',
  'Jerera Growth Point',
  'Gutu Mpandawana',
  'Masvingo CBD',
  'Harare CBD',
  'Harare - Borrowdale',
  'Harare - Avondale',
  'Harare - Mbare / Machipisa',
  'Harare - Eastgate / Sam Levy',
  'Bulawayo CBD',
  'Bulawayo - Hillside',
  'Mutare',
  'Gweru',
  'Kwekwe',
  'Chinhoyi',
  'Bindura',
  'Marondera',
  'Victoria Falls',
  'Beitbridge',
  'Zvishavane',
  'Chipinge',
  'Kariba',
  'Nandi',
] as const;
