import { Listing } from './types';

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'listing-001',
    userId: 'user-001',
    user: {
      id: 'user-001',
      phoneNumber: '+263772849102',
      fullName: 'Tinashe "Gudo" Mudavanhu',
      locationArea: 'Chiredzi Light Industry',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 38,
    },
    title: 'Heavy-Duty Sugarcane Trailer Fabrication & Leaf Spring Rebuild',
    description: 'Specialised in rebuilding 12-tonne and 20-tonne cane haulage trailers for the upcoming harvesting season. Complete heavy-gauge chassis reinforcement, new leaf spring mounting, drawbar fabrication, and brake air-line setup. Tested on rough estate roads.',
    category: 'industrial_services',
    currency: 'USD',
    price: 1850,
    barterTerms: 'Will accept 3 Brahman breeding heifers or 100 bags clean white maize as partial payment',
    locationArea: 'Chiredzi Light Industry',
    imageUrls: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['welding', 'trailer fabrication', 'sugarcane', 'heavy chassis', 'leaf spring'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: false,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-01T08:30:00Z',
  },
  {
    id: 'listing-002',
    userId: 'user-002',
    user: {
      id: 'user-002',
      phoneNumber: '+263719483019',
      fullName: 'Sekuru Phiri & Sons Livestock',
      locationArea: 'Mkwasine',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 52,
    },
    title: '4 Purebred Brahman Heifers (Drought-Hardy Lowveld Strain)',
    description: '4 healthy, tick-resistant Brahman heifers aged 18 to 22 months. Fully vaccinated for anthrax, quarter evil, and lumpy skin. Accustomed to Lowveld sweetveld pastures. Inspection welcome in Mkwasine section 12.',
    category: 'livestock_agric',
    currency: 'USD',
    price: 650, // Per heifer
    barterTerms: 'Open to barter: Need solar borehole pump system with 6x 450W panels or Massey Ferguson tractor disc plough',
    locationArea: 'Mkwasine',
    imageUrls: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['cattle', 'brahman heifers', 'livestock breeding', 'mkwasine cattle'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T10:15:00Z',
    updatedAt: '2026-09-01T10:15:00Z',
  },
  {
    id: 'listing-003',
    userId: 'user-003',
    user: {
      id: 'user-003',
      phoneNumber: '+263773190822',
      fullName: 'Farai Moyo Haulage',
      locationArea: 'Triangle Estate',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 5.0,
      tradeCount: 84,
    },
    title: '30-Tonne Cane & Bulk Agro Haulage (Tri-axle Flatbed & High Sides)',
    description: 'Available for contracted or ad-hoc sugarcane haulage from Mkwasine and Chipiwa outgrower plots to Hippo/Triangle mills. Also handles bulk fertilizer, cement loads, and timber from Beitbridge corridor.',
    category: 'transport_logistics',
    currency: 'ZAR',
    price: 3200, // ZAR per trip
    barterTerms: 'Can trade haulage services for 500L bulk diesel or commercial trailer tyres (315/80R22.5)',
    locationArea: 'Triangle Estate',
    imageUrls: [
      'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['truck hire', 'cane haulage', 'logistics', '30t truck', 'triangle'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: true,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T12:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'listing-004',
    userId: 'user-004',
    user: {
      id: 'user-004',
      phoneNumber: '+263784119044',
      fullName: 'Simba Nyathi Borehole Solutions',
      locationArea: 'Tshovani',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.7,
      tradeCount: 29,
    },
    title: 'Solar Borehole Pump Installation, Rewinding & PVC Casing Service',
    description: 'Certified water technician in Tshovani. We install Franklin, DAB, and Sunflo submersible solar pumps, troubleshoot controller faults, lower depths up to 120m, and install drip lines for horticulture plots. Fast response across Lowveld.',
    category: 'industrial_services',
    currency: 'USD',
    price: 280,
    barterTerms: 'Barter accepted: Will take 2 fat Boer goats, 15 bags maize grain, or sugarcane tops bundle delivery',
    locationArea: 'Tshovani',
    imageUrls: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['borehole repair', 'solar pumps', 'plumbing', 'tshovani artisan', 'water pump'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T14:20:00Z',
    updatedAt: '2026-09-01T14:20:00Z',
  },
  {
    id: 'listing-005',
    userId: 'user-005',
    user: {
      id: 'user-005',
      phoneNumber: '+263777620183',
      fullName: 'VaChauke Cane Feeders',
      locationArea: 'Hippo Valley',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: false,
      rating: 4.6,
      tradeCount: 19,
    },
    title: '500 Bundles Fresh Sugarcane Tops (Mashanga) - Drought Cattle Fodder',
    description: 'Freshly cut green sugarcane tops from Hippo Valley Section 26. High nutritive molasses value, best drought supplement for cattle and goats. Sold in bundles of 25kg each. Bakkie and truck collection welcome.',
    category: 'livestock_agric',
    currency: 'BARTER',
    price: null,
    barterTerms: 'Strict Barter: Seeking borehole repair service, plumbing fittings, or welding on cattle gate',
    locationArea: 'Hippo Valley',
    imageUrls: [
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['sugarcane tops', 'mashanga', 'cattle fodder', 'stockfeed', 'hippo valley'],
    conditionGrade: 'Used - Good',
    status: 'active',
    urgent: true,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T15:45:00Z',
    updatedAt: '2026-09-01T15:45:00Z',
  },
  {
    id: 'listing-006',
    userId: 'user-006',
    user: {
      id: 'user-006',
      phoneNumber: '+263712903847',
      fullName: 'Matibi Teak & Hardwood Joinery',
      locationArea: 'Tshovani',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 41,
    },
    title: 'Handcrafted Indigenous Teak 8-Seater Dining Set & Solid Panel Doors',
    description: 'Solid Zimbabwe Teak timber kiln dried and hand-carved in Tshovani. 8 heavy-duty chairs with cushioned seats plus matching 2.4m dining table. Also available: heavy teak front entrance pivot doors.',
    category: 'woodwork_construction',
    currency: 'USD',
    price: 750,
    barterTerms: 'Can swap for 1 healthy steer or 8 Kalahari Red goat ewes',
    locationArea: 'Tshovani',
    imageUrls: [
      'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['teak furniture', 'woodwork', 'carpentry', 'dining set', 'chiredzi doors'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T16:10:00Z',
    updatedAt: '2026-09-01T16:10:00Z',
  },
  {
    id: 'listing-007',
    userId: 'user-007',
    user: {
      id: 'user-007',
      phoneNumber: '+263778502941',
      fullName: 'Kudzai Solar & Musina Direct Spares',
      locationArea: 'Chiredzi Light Industry',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 67,
    },
    title: '5.5kVA Deye Hybrid Solar Inverter + 5.12kWh Felicity LiFePO4 Lithium Battery',
    description: 'Direct import from South Africa via Beitbridge. Brand new in box with 5-year manufacturer warranty. Runs entire household + borehole pump during ZESA load shedding. Includes installation bracket and cables.',
    category: 'retail_hardware',
    currency: 'USD',
    price: 1250,
    barterTerms: 'Can accept 2 Brahman cows or trade for 15-tonne tipper sand and gravel loads',
    locationArea: 'Chiredzi Light Industry',
    imageUrls: [
      'https://images.unsplash.com/photo-1508873696983-2df515122519?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['solar inverter', 'lithium battery', 'deye', 'power backup', 'solar system'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T17:00:00Z',
    updatedAt: '2026-09-01T17:00:00Z',
  },
  {
    id: 'listing-008',
    userId: 'user-008',
    user: {
      id: 'user-008',
      phoneNumber: '+263774910283',
      fullName: 'Tafadzwa Gumbo Plumber & Builder',
      locationArea: 'Buffalo Range',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.7,
      tradeCount: 22,
    },
    title: 'Septic Tank Excavation, French Drain & Domestic Plumbing Installs',
    description: 'Residential and commercial plumbing contractor. We build complete brick septic systems, grease traps, soakaways, copper/PEX water piping, geyser installations, and tank stands in Fairview, Tshovani, and Buffalo Range.',
    category: 'woodwork_construction',
    currency: 'USD',
    price: 350,
    barterTerms: 'Open to trade: Need welding work on 5000L water tank stand or 40 bags PPC cement',
    locationArea: 'Buffalo Range',
    imageUrls: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['plumbing', 'septic tank', 'construction', 'buffalo range', 'water tank stand'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T18:30:00Z',
    updatedAt: '2026-09-01T18:30:00Z',
  },
  {
    id: 'listing-009',
    userId: 'user-009',
    user: {
      id: 'user-009',
      phoneNumber: '+263771829304',
      fullName: 'Mbuya Sibanda Free Range Farm',
      locationArea: 'Malipati',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: false,
      rating: 4.9,
      tradeCount: 35,
    },
    title: '15 Breeding Matabele & Boer Cross Goats (Healthy Does & Bucks)',
    description: 'Hardy Malipati stock, excellent for starting a herd or meat production. 12 young does ready to breed and 3 active stud bucks. Raised in thornveld browse, zero supplementary feed required. Delivery to Chiredzi town negotiable.',
    category: 'livestock_agric',
    currency: 'ZAR',
    price: 850, // Per goat ZAR
    barterTerms: 'Barter accepted: Need 10 rolls of barbed wire / cattle fencing or 1.5kW solar pump',
    locationArea: 'Malipati',
    imageUrls: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1563865436874-9aef32095fad?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['goats', 'boer goats', 'malipati', 'livestock', 'breeding does'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T19:00:00Z',
    updatedAt: '2026-09-01T19:00:00Z',
  },
  {
    id: 'listing-010',
    userId: 'user-010',
    user: {
      id: 'user-010',
      phoneNumber: '+263782940173',
      fullName: 'Lovemore Bakkie Hire Tshovani',
      locationArea: 'Tshovani',
      avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 93,
    },
    title: '1-Tonne Isuzu KB Bakkie Hire (Local Tshovani, Light Industry & Hippo Valley)',
    description: 'Fast, reliable drops for cement, groceries, welding materials, timber, and produce. 24/7 on call in Tshovani. Trips starting from $10 USD / 180 ZAR within town. Also available for farm produce pickups.',
    category: 'transport_logistics',
    currency: 'USD',
    price: 15,
    barterTerms: 'Open to barter: Fuel vouchers, mechanical servicing, or bags of grain',
    locationArea: 'Tshovani',
    imageUrls: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['bakkie hire', 'tshovani transport', 'isuzu pickup', 'deliveries'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: true,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T19:40:00Z',
    updatedAt: '2026-09-01T19:40:00Z',
  },
];
