import { Listing } from './types';

export const INITIAL_LISTINGS: Listing[] = [
  {
    id: 'listing-001',
    userId: 'user-001',
    user: {
      id: 'user-001',
      phoneNumber: '+263772849102',
      fullName: 'Tinashe "Gudo" Mudavanhu Engineering',
      locationArea: 'Harare - Workington',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 38,
    },
    title: 'Heavy-Duty Sugarcane & Farm Haulage Trailer Fabrication',
    description: 'Specialised in building and rebuilding 12-tonne to 20-tonne agricultural haulage trailers. Heavy-gauge reinforced chassis, new multi-leaf spring suspension, drawbar fabrication, and dual-line air brake fittings. Tested for rugged estate and farm roads.',
    category: 'industrial_services',
    currency: 'USD',
    price: 1850,
    barterTerms: 'Will accept 3 Brahman breeding heifers or 120 bags clean white Grade A maize as partial barter exchange',
    locationArea: 'Harare - Workington',
    imageUrls: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['welding', 'trailer fabrication', 'haulage', 'heavy chassis', 'leaf spring'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: false,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-01T08:30:00Z',
  },
  {
    id: 'listing-002',
    userId: 'user-002',
    user: {
      id: 'user-002',
      phoneNumber: '+263719483019',
      fullName: 'Sekuru Phiri & Sons Livestock Ranches',
      locationArea: 'Bulawayo - Hillside',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 52,
    },
    title: '4 Purebred Brahman Heifers (Drought-Hardy Sweetveld Strain)',
    description: '4 healthy, tick-resistant Brahman heifers aged 18 to 22 months. Fully vaccinated for anthrax, quarter evil, and lumpy skin disease. Accustomed to harsh sweetveld rangeland. Veterinary inspection and clearance papers ready.',
    category: 'livestock_agric',
    currency: 'USD',
    price: 650,
    barterTerms: 'Open to barter: Need solar borehole pump kit with 6x 550W Canadian solar panels or Massey Ferguson tractor disc plough',
    locationArea: 'Bulawayo - Hillside',
    imageUrls: [
      'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['cattle', 'brahman heifers', 'livestock breeding', 'bulawayo cattle'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T10:15:00Z',
    updatedAt: '2026-09-01T10:15:00Z',
  },
  {
    id: 'listing-003',
    userId: 'user-003',
    user: {
      id: 'user-003',
      phoneNumber: '+263773194850',
      fullName: 'Farai Moyo Cross-Border Haulage',
      locationArea: 'Beitbridge',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 5.0,
      tradeCount: 84,
    },
    title: '30-Tonne Tri-Axle Flatbed Haulage (Beitbridge • Masvingo • Harare Corridor)',
    description: 'Available for contracted bulk agro produce, fertilizer, cement, timber, and commercial equipment haulage. Experienced drivers with valid cross-border permits and GIT insurance cover. Fast transit turnaround times.',
    category: 'transport_logistics',
    currency: 'ZAR',
    price: 3200,
    barterTerms: 'Can trade haulage trips for 500L clean diesel fuel coupons or commercial trailer tyres (315/80R22.5)',
    locationArea: 'Beitbridge',
    imageUrls: [
      'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['truck hire', 'flatbed haulage', 'logistics', '30t truck', 'beitbridge'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: true,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T12:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'listing-004',
    userId: 'user-004',
    user: {
      id: 'user-004',
      phoneNumber: '+263784102938',
      fullName: 'Simba Nyathi Borehole Solutions',
      locationArea: 'Masvingo',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 29,
    },
    title: 'Solar Borehole Pump Installation, Depth Testing & PVC Casing Service',
    description: 'Certified water engineer covering Masvingo, Chiredzi, Zvishavane, and Gutu. We install Franklin Electric, DAB, and Sunflo submersible pumps, lower pump sets up to 140m, connect automatic pressure control tanks, and run drip irrigation lines.',
    category: 'industrial_services',
    currency: 'USD',
    price: 280,
    barterTerms: 'Barter accepted: Will accept 2 Boer breeding goats, 18 bags clean maize grain, or 35 bags PPC cement',
    locationArea: 'Masvingo',
    imageUrls: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['borehole repair', 'solar pumps', 'plumbing', 'masvingo artisan', 'water pump'],
    conditionGrade: 'Service Showcase',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T14:20:00Z',
    updatedAt: '2026-09-01T14:20:00Z',
  },
  {
    id: 'listing-005',
    userId: 'user-005',
    user: {
      id: 'user-005',
      phoneNumber: '+263783237918',
      fullName: 'VaChauke Lowveld Outgrowers',
      locationArea: 'Chiredzi / Triangle',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: false,
      rating: 4.7,
      tradeCount: 19,
    },
    title: '500 Bundles Fresh Green Sugarcane Tops (Mashanga) - Drought Cattle Fodder',
    description: 'Fresh cut nutrient-dense sugarcane tops from Hippo Valley Section 26. High residual sucrose and moisture value, the ideal drought survival supplement for cattle herds and goats during dry months. Sold in 25kg bundles with truck loading on site.',
    category: 'livestock_agric',
    currency: 'BARTER',
    price: null,
    barterTerms: 'Strict Barter: Seeking borehole solar controller repair, 10 rolls high-tensile fencing wire, or welding on cattle kraal gates',
    locationArea: 'Chiredzi / Triangle',
    imageUrls: [
      'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['sugarcane tops', 'mashanga', 'cattle fodder', 'stockfeed', 'chiredzi trade'],
    conditionGrade: 'Used - Good',
    status: 'active',
    urgent: true,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T15:45:00Z',
    updatedAt: '2026-09-01T15:45:00Z',
  },
  {
    id: 'listing-006',
    userId: 'user-006',
    user: {
      id: 'user-006',
      phoneNumber: '+263774902184',
      fullName: 'Eastern Highlands Hardwood & Joinery',
      locationArea: 'Mutare',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 41,
    },
    title: 'Handcrafted Solid Indigenous Teak & Mukwa 8-Seater Dining Suite',
    description: 'Solid Zimbabwe Teak and Mukwa timber kiln dried and handcrafted in Mutare. 8 reinforced chairs with durable upholstery plus heavy 2.4m banquet dining table. Resistant to borer beetles and moisture. Delivery arranged across Zimbabwe.',
    category: 'woodwork_construction',
    currency: 'USD',
    price: 750,
    barterTerms: 'Can swap for 1 healthy slaughter steer or 8 quality Boer goat breeding does',
    locationArea: 'Mutare',
    imageUrls: [
      'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['teak furniture', 'woodwork', 'mukwa', 'dining suite', 'mutare joinery'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T16:10:00Z',
    updatedAt: '2026-09-01T16:10:00Z',
  },
  {
    id: 'listing-007',
    userId: 'user-007',
    user: {
      id: 'user-007',
      phoneNumber: '+263772591024',
      fullName: 'Kudzai Solar & Musina Direct Spares',
      locationArea: 'Harare - Borrowdale',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 67,
    },
    title: '6kVA Deye Hybrid Inverter + 5.12kWh Felicity LiFePO4 Lithium Battery System',
    description: 'Brand new in box with 5-year factory warranty and local backup support. Powers entire residence, borehole pump, cold-room refrigeration, and computers during load shedding. Includes mounting bracket, 25mm battery cables, and Wi-Fi monitoring dongle.',
    category: 'retail_hardware',
    currency: 'USD',
    price: 1350,
    barterTerms: 'Can accept 2 Brahman cows or trade for 15-tonne tipper delivery of washed quarry gravel stone and river sand',
    locationArea: 'Harare - Borrowdale',
    imageUrls: [
      'https://images.unsplash.com/photo-1508873696983-2df515122519?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['solar inverter', 'lithium battery', 'deye', 'power backup', 'harare solar'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T17:00:00Z',
    updatedAt: '2026-09-01T17:00:00Z',
  },
  {
    id: 'listing-008',
    userId: 'user-008',
    user: {
      id: 'user-008',
      phoneNumber: '+263712849203',
      fullName: 'Midlands Agro Lime & Mineral Feeds',
      locationArea: 'Gweru',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 22,
    },
    title: 'Agricultural Calcitic Lime (50kg bags) & Cattle Salt Licks',
    description: 'Soil de-acidification agricultural lime for commercial maize, tobacco, and wheat plots in Gweru, Kwekwe, and Shurugwi. Improves fertilizer absorption up to 40%. Also available: 20kg weather-resistant macro-mineral livestock lick blocks.',
    category: 'livestock_agric',
    currency: 'USD',
    price: 6.5,
    barterTerms: 'Open to barter: Need diesel fuel coupons, second-hand 14-ply tractor tyres, or 50kg bags of urea top dressing',
    locationArea: 'Gweru',
    imageUrls: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['agricultural lime', 'soil conditioning', 'mineral licks', 'gweru agro', 'stockfeed'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T18:30:00Z',
    updatedAt: '2026-09-01T18:30:00Z',
  },
  {
    id: 'listing-009',
    userId: 'user-009',
    user: {
      id: 'user-009',
      phoneNumber: '+263773819204',
      fullName: 'Mbuya Sibanda Free Range Livestock Hub',
      locationArea: 'Bulawayo CBD',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: false,
      rating: 4.9,
      tradeCount: 35,
    },
    title: '15 Breeding Matabele & Kalahari Red Cross Goats (Healthy Does & Stud Buck)',
    description: 'High-fertility, drought-adapted breed from Gwanda rangelands. 12 young does ready to kid and 3 active stud bucks. Excellent meat conformation, raised on acacia browse. Inspection and collection welcome in Bulawayo or delivery along main highway.',
    category: 'livestock_agric',
    currency: 'ZAR',
    price: 850,
    barterTerms: 'Barter accepted: Need 12 rolls of diamond mesh cattle fencing wire or 1.5kW solar submersible borehole pump',
    locationArea: 'Bulawayo CBD',
    imageUrls: [
      'https://images.unsplash.com/photo-1524024973431-2ad916746881?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1563865436874-9aef32095fad?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['goats', 'boer goats', 'kalahari red', 'livestock', 'matabeleland'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-01T19:00:00Z',
    updatedAt: '2026-09-01T19:00:00Z',
  },
  {
    id: 'listing-010',
    userId: 'user-010',
    user: {
      id: 'user-010',
      phoneNumber: '+263771987654',
      fullName: 'Mbare Musika Grain & Wholesale Direct',
      locationArea: 'Harare - Mbare / Machipisa',
      avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.9,
      tradeCount: 93,
    },
    title: 'Wholesale White Maize (50kg Bags), Sugar Beans & Roundnuts (Nyimo)',
    description: 'Bulk grain supply directly from Mashonaland farming belts. Clean, moisture-tested white maize grain in 50kg sacks, premium grade sugar beans, and dried nyimo/ndlubu. Bulk orders packed for retail wholesalers, supermarkets, and boarding schools.',
    category: 'grocery_wholesale',
    currency: 'USD',
    price: 18,
    barterTerms: 'Will trade for diesel fuel vouchers, 3-tonne bakkie transport trips, or packaging bags supply',
    locationArea: 'Harare - Mbare / Machipisa',
    imageUrls: [
      'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['maize grain', 'sugar beans', 'mbare musika', 'bulk food', 'harare wholesale'],
    conditionGrade: 'New',
    status: 'active',
    urgent: true,
    harvestReady: true,
    openToBarter: true,
    createdAt: '2026-09-01T19:40:00Z',
    updatedAt: '2026-09-01T19:40:00Z',
  },
  {
    id: 'listing-011',
    userId: 'user-011',
    user: {
      id: 'user-011',
      phoneNumber: '+263772849103',
      fullName: 'PPC & Lafarge Certified Construction Depot',
      locationArea: 'Harare CBD',
      avatarUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 5.0,
      tradeCount: 112,
    },
    title: 'PPC Surebuild 42.5N Cement (50kg), Y12 Rebar & Concrete Blocks',
    description: 'High-strength structural building supplies delivered on-site across Greater Harare, Ruwa, Norton, and Chitungwiza. Official distributor of PPC 42.5N and 32.5R, deformed high-tensile steel reinforcing bars (Y10, Y12, Y16), and machine-vibrated solid blocks.',
    category: 'building_construction',
    currency: 'USD',
    price: 10.5,
    barterTerms: 'Will accept trade for cattle steers, 10-tonne tipper gravel drops, or solar inverter backup system',
    locationArea: 'Harare CBD',
    imageUrls: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['cement', 'rebar', 'building construction', 'hardware', 'harare construction'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-02T10:15:00Z',
    updatedAt: '2026-09-02T10:15:00Z',
  },
  {
    id: 'listing-012',
    userId: 'user-012',
    user: {
      id: 'user-012',
      phoneNumber: '+263719827361',
      fullName: 'Victoria Falls & Zambezi Solar Cold Storage',
      locationArea: 'Victoria Falls',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      verifiedArtisan: true,
      rating: 4.8,
      tradeCount: 27,
    },
    title: 'Solar-Powered Walk-In Cold Room & Blast Chiller Installation',
    description: 'Commercial refrigeration systems engineered for hot climates (Matabeleland North & Lowveld). Keep fresh farm produce, beef carcases, and butchery supplies at -2°C to 4°C with zero ZESA dependence. Complete with insulated polyurethane modular panels.',
    category: 'industrial_services',
    currency: 'USD',
    price: 3400,
    barterTerms: 'Open to barter: 5 Brahman heifers, 1-tonne commercial bakkie vehicle, or 500 bags certified seed maize',
    locationArea: 'Victoria Falls',
    imageUrls: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
    ],
    imageTags: ['cold room', 'solar refrigeration', 'butchery equipment', 'vic falls', 'chiller'],
    conditionGrade: 'New',
    status: 'active',
    urgent: false,
    harvestReady: false,
    openToBarter: true,
    createdAt: '2026-09-02T11:20:00Z',
    updatedAt: '2026-09-02T11:20:00Z',
  }
];
